### ISSUE TITLE
car_size.pth not found

### ISSUE THREAD

**Issue by ErshadBanijamali** [Atcold/pytorch-PPUU#15]
I get an error indicating that "car_size.pth" not found. 

`python train_fm.py -model_dir <fm_save_path>`

**Comment by Atcold** [comment]
Please, run [`extract_car_size.py`](https://github.com/Atcold/pytorch-PPUU/blob/master/extract_car_size.py).

**Comment by ErshadBanijamali** [comment]
Thank you! Now I get this error by running the same line of the code. From the dataloader.py:

`car_id  = int(re.findall('car(\d+).pkl',splits[5])[0])`
`IndexError: list index out of range`

Any idea?

**Comment by Atcold** [comment]
Hi, plz, check this commit https://github.com/Atcold/pytorch-PPUU/commit/a83b83b1596a0749c67406977f06ebe7f9cc9e27
