### ISSUE TITLE
matplotlib is missing from the environment

### ISSUE THREAD

**Issue by adegirmenci** [Atcold/pytorch-PPUU#19]
`ModuleNotFoundError: No module named 'matplotlib'`
and
`ModuleNotFoundError: No module named 'sklearn'`

**Comment by Atcold** [comment]
What scripts is generating these errors?

**Comment by yair-schiff** [comment]
I received the same error. 

Both of these packages are imported in `utils.py`

**Comment by Atcold** [comment]
Fixed.
