### ISSUE TITLE
Predicted costs is list object in planning.py

### ISSUE THREAD

**Issue by yair-schiff** [Atcold/pytorch-PPUU#23]
I receive the following error when running `train_MPUR.py` and `train_cost.py`:
```
planning.py", line 86, in compute_uncertainty_batch
       pred_costs  = pred_costs. view(n_models, bsize, npred, -1)
       AttributeError: 'list' object has no attribute 'view'
```

Is this because I am using a regular `fwd-cnn` model? Do I need to use `fwd-cnn-vae-fp` in order to ensure that pred_costs is generated correctly?

**Comment by Atcold** [comment]
Currently we're using `fwd-cnn-vae-fp`, which is our *action conditional variational predictive model*.
The `fwd-cnn` version is simply the deterministic variant (without latent variables), which used to work.
But year, you should use the former (although the latter should run as well).

**Comment by yair-schiff** [comment]
Makes sense. However `planning.py` still throws an error in line 86 since `pred_costs` is a list and we perform the torch tensor `view` function on it. 

Is it okay to replace that line as follows:

~pred_costs  = pred_costs. view(n_models, bsize, npred, -1)~
```
pred_costs = torch.Tensor(n_models, bsize, npred, 1)
```
i.e. manually create a new tensor that has shape `n_models, bsize, npred, 1`?

**Comment by Atcold** [comment]
Hmm, `planning.py` is working just fine for me.
Are we using different versions?

**Comment by yair-schiff** [comment]
I will try running the code as it is on `master` for us-101 data and see if the error persists and let you know

**Comment by Atcold** [comment]
Do we know what happened here?
