### ISSUE TITLE
get_batch_fm gets additional index

### ISSUE THREAD

**Issue by yair-schiff** [Atcold/pytorch-PPUU#26]
In `get_batch_fm` method in `dataloader.py`, `self.opt.ncond + npred + 1` number of images, states, and actions are loaded:
```
images.append(self.images[s][t:t+(self.opt.ncond+npred)+1].cuda())
actions.append(self.actions[s][t:t+(self.opt.ncond+npred)].cuda())
states.append(self.states[s][t:t+(self.opt.ncond+npred)+1].cuda())
costs.append(self.costs[s][t:t+(self.opt.ncond+npred)+1].cuda())
```
Note that only `self.opt.ncond + npred` number of actions are loaded.
It is not clear why there is a `+1` for the other variables.

Additionally, when using `US101` dataset, there was an error because number of `self.states[s].size(0)` exceeded that `self.images[s].size(0)`, therefore need to make the following adjustment to line 154 of code:
~T = self.states[s].size(0)~
```
T = min(self.images[s].size(0), self.states[s].size(0))
```

**Comment by Atcold** [comment]
If that `+1` is everything still running fine?

**Comment by yair-schiff** [comment]
Yes, things seem to be running ok with the `+1` on `images`, `states`, and `costs`

**Comment by Atcold** [comment]
For both `I-80` and `US-101`?
If so, plz, send a PR.

**Comment by yair-schiff** [comment]
I believe this was merged in #27

**Comment by Atcold** [comment]
This is on the current `master`: https://github.com/Atcold/pytorch-PPUU/blob/316159e7f51155e304d43f0ad03dac05c6903509/dataloader.py#L158-L163
```python
if T > (self.opt.ncond + npred + 1):
    t = self.random.randint(0, T - (self.opt.ncond+npred+1))
    images.append(self.images[s][t:t+(self.opt.ncond+npred)+1].to(device))
    actions.append(self.actions[s][t:t+(self.opt.ncond+npred)].to(device))
    states.append(self.states[s][t:t+(self.opt.ncond+npred)+1].to(device))
    costs.append(self.costs[s][t:t+(self.opt.ncond+npred)+1].to(device))
```
I'm wondering whether we need the extra `+1`.

**Comment by Atcold** [comment]
We return only values up to `ncond + npred`, so this `+1` is doing nothing here.
See below: https://github.com/Atcold/pytorch-PPUU/blob/316159e7f51155e304d43f0ad03dac05c6903509/dataloader.py#L189-L200

**Comment by Atcold** [comment]
More unnecessary `+1`s.
https://github.com/Atcold/pytorch-PPUU/blob/316159e7f51155e304d43f0ad03dac05c6903509/dataloader.py#L92-L95
