### ISSUE TITLE
Sampling rate of data used

### ISSUE THREAD

**Issue by timo-sievernich** [Atcold/pytorch-PPUU#65]
Hi PPUU-Team,

I'd like to estimate the planning horizon in seconds of your algorithm.

I'm wondering, what sample rate did you used for generating your data (images, states, actions, costs, ...)? 
With regard to the "Global Time" entry in the file "./traffic-data/xy-trajectories/i80/trajectories-0500-0515.txt" the sampling rate should be 10 fps. Is this correct?

Thanks,
Timo

**Comment by Atcold** [comment]
Yes, 10 fps.
