### ISSUE TITLE
Issue in dumping "state, action, cost" triple

### ISSUE THREAD

**Issue by jayabrata97** [Atcold/pytorch-PPUU#67]
I was trying run `generate_trajectories.py`. However, it was giving error `TypeError: step() missing 1 required positional argument: 'action'` on line 90 `observation, reward, done, info = env.step()`. I changed it to `observation, reward, done, info = env.step(np.zeros((2,)))`. Then it started building pkl files. @Atcold , is it correct?

**Comment by lucywang720** [comment]
I have the same problem, do you solve it?

**Comment by jayabrata97** [comment]
Yes.

**Comment by lucywang720** [comment]
So observation, reward, done, info = env.step(np.zeros((2,))) is correct or not?

**Comment by jayabrata97** [comment]
> So observation, reward, done, info = env.step(np.zeros((2,))) is correct or not?

Correct, it worked for me.

**Comment by lucywang720** [comment]
> > So observation, reward, done, info = env.step(np.zeros((2,))) is correct or not?
> 
> Correct, it worked for me.

Thank you a lot!!

**Comment by Atcold** [comment]
Can you send a patch to fix this issue?

**Comment by jayabrata97** [comment]
Hi @Atcold, https://github.com/Atcold/pytorch-PPUU/blob/2e087d9ef556cf75723ff2c5f5b71c4bb0b358dc/generate_trajectories.py#L90

I changed this line.
By the way, thanks for the deep learning course lectures. I came to know about the paper from there.

**Comment by Atcold** [comment]
I meant asking whether you'd like to send a PR and/or edit the file directly.
So you'll be a contributor ;)

**Comment by jayabrata97** [comment]
Hi @Atcold, sorry for the late reply. I would like to edit the file directly. Thank you very much for considering me as a contributor.

**Comment by Atcold** [comment]
Just click on the ✏️ and edit the file.
Don't forget to type "close #67" in your commit message to automatically close this issue.
